name: Build Swing Plus APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Flutter SDK
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

   # - name: Re-create Missing Android Skeleton
   #   run: flutter create . --platforms=android --org=com.swingplus.app

    - name: Get Dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release --no-tree-shake-icons

    - name: Upload APK File
      uses: actions/upload-artifact@v4
      with:
        name: SwingPlus-APK
        path: build/app/outputs/flutter-apk/app-release.apk
